[workspace]
authors = ["whtns <kevin.stachelek@gmail.com>"]
channels = ["conda-forge"]
name = "grthub_bclconvert"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.grthub-bclconvert]
platforms = ["linux-64"]
channels = ["bioconda", "conda-forge"]

[feature.grthub-bclconvert.target.linux-64.dependencies]
_libgcc_mutex = { version = "==0.1", build = "conda_forge" }
_openmp_mutex = { version = "==4.5", build = "2_gnu" }
alsa-lib = { version = "==1.2.14", build = "hb9d3cd8_0" }
amply = { version = "==0.1.6", build = "pyhd8ed1ab_1" }
annotated-types = { version = "==0.7.0", build = "pyhd8ed1ab_1" }
appdirs = { version = "==1.4.4", build = "pyhd8ed1ab_1" }
argparse-dataclass = { version = "==2.0.0", build = "pyhd8ed1ab_1" }
asttokens = { version = "==3.0.1", build = "pyhd8ed1ab_0" }
attrs = { version = "==25.4.0", build = "pyhcf101f3_1" }
"backports.zstd" = { version = "==1.2.0", build = "py312h90b7ffd_0" }
brotli = { version = "==1.2.0", build = "hed03a55_1" }
brotli-bin = { version = "==1.2.0", build = "hb03c661_1" }
brotli-python = { version = "==1.2.0", build = "py312hdb49522_1" }
bzip2 = { version = "==1.0.8", build = "hda65f42_8" }
ca-certificates = { version = "==2025.11.12", build = "hbd8a1cb_0" }
cairo = { version = "==1.18.4", build = "h3394656_0" }
certifi = { version = "==2025.11.12", build = "pyhd8ed1ab_0" }
charset-normalizer = { version = "==3.4.4", build = "pyhd8ed1ab_0" }
click = { version = "==8.3.1", build = "pyh8f84b5b_1" }
coin-or-cbc = { version = "==2.10.12", build = "h4d16d09_4" }
coin-or-cgl = { version = "==0.60.9", build = "hc46dffc_6" }
coin-or-clp = { version = "==1.17.10", build = "hc03379b_3" }
coin-or-osi = { version = "==0.108.11", build = "hf4fecb4_8" }
coin-or-utils = { version = "==2.11.12", build = "hc93afbd_7" }
colorama = { version = "==0.4.6", build = "pyhd8ed1ab_1" }
coloredlogs = { version = "==15.0.1", build = "pyhd8ed1ab_4" }
conda-inject = { version = "==1.3.2", build = "pyhd8ed1ab_0" }
configargparse = { version = "==1.7.1", build = "pyhe01879c_0" }
connection_pool = { version = "==0.0.3", build = "pyhd3deb0d_0" }
contourpy = { version = "==1.3.3", build = "py312hd9148b4_3" }
cycler = { version = "==0.12.1", build = "pyhcf101f3_2" }
cyrus-sasl = { version = "==2.1.28", build = "hd9c7081_0" }
dbus = { version = "==1.16.2", build = "h24cb091_1" }
decorator = { version = "==5.2.1", build = "pyhd8ed1ab_0" }
docutils = { version = "==0.22.3", build = "pyhd8ed1ab_0" }
double-conversion = { version = "==3.4.0", build = "hecca717_0" }
dpath = { version = "==2.2.0", build = "pyha770c72_1" }
eido = { version = "==0.2.4", build = "pyhd8ed1ab_0" }
et_xmlfile = { version = "==2.0.0", build = "pyhd8ed1ab_1" }
exceptiongroup = { version = "==1.3.1", build = "pyhd8ed1ab_0" }
executing = { version = "==2.2.1", build = "pyhd8ed1ab_0" }
fastqc = { version = "==0.12.1", build = "hdfd78af_0" }
flexbar = { version = "==3.5.0", build = "hdfd68b8_12" }
font-ttf-dejavu-sans-mono = { version = "==2.37", build = "hab24e00_0" }
font-ttf-inconsolata = { version = "==3.0", build = "h77eed37_0" }
font-ttf-source-code-pro = { version = "==2.38", build = "h77eed37_0" }
font-ttf-ubuntu = { version = "==0.83", build = "h77eed37_3" }
fontconfig = { version = "==2.15.0", build = "h7e30c49_1" }
fonts-conda-ecosystem = { version = "==1", build = "0" }
fonts-conda-forge = { version = "==1", build = "hc364b38_1" }
fonttools = { version = "==4.61.1", build = "py312h8a5da7c_0" }
freetype = { version = "==2.14.1", build = "ha770c72_0" }
giflib = { version = "==5.2.2", build = "hd590300_0" }
gitdb = { version = "==4.0.12", build = "pyhd8ed1ab_0" }
gitpython = { version = "==3.1.45", build = "pyhff2d567_0" }
graphite2 = { version = "==1.3.14", build = "hecca717_2" }
h2 = { version = "==4.3.0", build = "pyhcf101f3_0" }
harfbuzz = { version = "==12.2.0", build = "h15599e2_0" }
hpack = { version = "==4.1.0", build = "pyhd8ed1ab_0" }
humanfriendly = { version = "==10.0", build = "pyh707e725_8" }
hyperframe = { version = "==6.1.0", build = "pyhd8ed1ab_0" }
icu = { version = "==75.1", build = "he02047a_0" }
idna = { version = "==3.11", build = "pyhd8ed1ab_0" }
immutables = { version = "==0.21", build = "py312h4c3975b_2" }
iniconfig = { version = "==2.3.0", build = "pyhd8ed1ab_0" }
ipython = { version = "==9.8.0", build = "pyh53cf698_0" }
ipython_pygments_lexers = { version = "==1.1.1", build = "pyhd8ed1ab_0" }
jedi = { version = "==0.19.2", build = "pyhd8ed1ab_1" }
jinja2 = { version = "==3.1.6", build = "pyhcf101f3_1" }
jsonschema = { version = "==4.25.1", build = "pyhe01879c_0" }
jsonschema-specifications = { version = "==2025.9.1", build = "pyhcf101f3_0" }
jupyter_core = { version = "==5.9.1", build = "pyhc90fa1f_0" }
keyutils = { version = "==1.6.3", build = "hb9d3cd8_0" }
kiwisolver = { version = "==1.4.9", build = "py312h0a2e395_2" }
krb5 = { version = "==1.21.3", build = "h659f571_0" }
lcms2 = { version = "==2.17", build = "h717163a_0" }
ld_impl_linux-64 = { version = "==2.45", build = "default_hbd61a6d_104" }
lerc = { version = "==4.0.0", build = "h0aef613_1" }
libblas = { version = "==3.11.0", build = "5_h4a7cf45_openblas" }
libbrotlicommon = { version = "==1.2.0", build = "hb03c661_1" }
libbrotlidec = { version = "==1.2.0", build = "hb03c661_1" }
libbrotlienc = { version = "==1.2.0", build = "hb03c661_1" }
libcblas = { version = "==3.11.0", build = "5_h0358290_openblas" }
"libclang-cpp21.1" = { version = "==21.1.7", build = "default_h99862b1_1" }
libclang13 = { version = "==21.1.7", build = "default_h746c552_1" }
libcups = { version = "==2.3.3", build = "hb8b1518_5" }
libdeflate = { version = "==1.25", build = "h17f619e_0" }
libdrm = { version = "==2.4.125", build = "hb03c661_1" }
libedit = { version = "==3.1.20250104", build = "pl5321h7949ede_0" }
libegl = { version = "==1.7.0", build = "ha4b6fd6_2" }
libexpat = { version = "==2.7.3", build = "hecca717_0" }
libffi = { version = "==3.5.2", build = "h9ec8514_0" }
libfreetype = { version = "==2.14.1", build = "ha770c72_0" }
libfreetype6 = { version = "==2.14.1", build = "h73754d4_0" }
libgcc = { version = "==15.2.0", build = "he0feb66_16" }
libgcc-ng = { version = "==15.2.0", build = "h69a702a_16" }
libgfortran = { version = "==15.2.0", build = "h69a702a_16" }
libgfortran5 = { version = "==15.2.0", build = "h68bc16d_16" }
libgl = { version = "==1.7.0", build = "ha4b6fd6_2" }
libglib = { version = "==2.86.3", build = "h6548e54_0" }
libglvnd = { version = "==1.7.0", build = "ha4b6fd6_2" }
libglx = { version = "==1.7.0", build = "ha4b6fd6_2" }
libgomp = { version = "==15.2.0", build = "he0feb66_16" }
libhwloc = { version = "==2.12.1", build = "default_hafda6a7_1003" }
libiconv = { version = "==1.18", build = "h3b78370_2" }
libjpeg-turbo = { version = "==3.1.2", build = "hb03c661_0" }
liblapack = { version = "==3.11.0", build = "5_h47877c9_openblas" }
liblapacke = { version = "==3.11.0", build = "5_h6ae95b6_openblas" }
libllvm21 = { version = "==21.1.7", build = "hf7376ad_0" }
liblzma = { version = "==5.8.1", build = "hb9d3cd8_2" }
libnsl = { version = "==2.0.1", build = "hb9d3cd8_1" }
libntlm = { version = "==1.8", build = "hb9d3cd8_0" }
libopenblas = { version = "==0.3.30", build = "pthreads_h94d23a6_4" }
libopengl = { version = "==1.7.0", build = "ha4b6fd6_2" }
libpciaccess = { version = "==0.18", build = "hb9d3cd8_0" }
libpng = { version = "==1.6.53", build = "h421ea60_0" }
libpq = { version = "==18.1", build = "h5c52fec_2" }
libsqlite = { version = "==3.51.1", build = "h0c1763c_0" }
libstdcxx = { version = "==15.2.0", build = "h934c35e_16" }
libstdcxx-ng = { version = "==15.2.0", build = "hdf11a46_16" }
libtiff = { version = "==4.7.1", build = "h9d88235_1" }
libuuid = { version = "==2.41.2", build = "h5347b49_1" }
libvulkan-loader = { version = "==1.4.328.1", build = "h5279c79_0" }
libwebp-base = { version = "==1.6.0", build = "hd42ef1d_0" }
libxcb = { version = "==1.17.0", build = "h8a09558_0" }
libxcrypt = { version = "==4.4.36", build = "hd590300_1" }
libxkbcommon = { version = "==1.13.1", build = "hca5e8e5_0" }
libxml2 = { version = "==2.15.1", build = "h26afc86_0" }
libxml2-16 = { version = "==2.15.1", build = "ha9997c6_0" }
libxslt = { version = "==1.1.43", build = "h711ed8c_1" }
libzlib = { version = "==1.3.1", build = "hb9d3cd8_2" }
logmuse = { version = "==0.2.8", build = "pyhd8ed1ab_1" }
markdown-it-py = { version = "==4.0.0", build = "pyhd8ed1ab_0" }
markupsafe = { version = "==3.0.3", build = "py312h8a5da7c_0" }
matplotlib = { version = "==3.10.8", build = "py312h7900ff3_0" }
matplotlib-base = { version = "==3.10.8", build = "py312he3d6523_0" }
matplotlib-inline = { version = "==0.2.1", build = "pyhd8ed1ab_0" }
mdurl = { version = "==0.1.2", build = "pyhd8ed1ab_1" }
munkres = { version = "==1.1.4", build = "pyhd8ed1ab_1" }
nbformat = { version = "==5.10.4", build = "pyhd8ed1ab_1" }
ncurses = { version = "==6.5", build = "h2d0b736_3" }
numpy = { version = "==2.3.5", build = "py312h33ff503_0" }
openjdk = { version = "==25.0.1", build = "h5755bd7_0" }
openjpeg = { version = "==2.5.4", build = "h55fea9a_0" }
openldap = { version = "==2.6.10", build = "he970967_0" }
openpyxl = { version = "==3.1.5", build = "py312h7f6eeab_2" }
openssl = { version = "==3.6.0", build = "h26f9b46_0" }
packaging = { version = "==25.0", build = "pyh29332c3_1" }
pandas = { version = "==2.3.3", build = "py312hf79963d_1" }
parso = { version = "==0.8.5", build = "pyhcf101f3_0" }
pcre2 = { version = "==10.47", build = "haa7fec5_0" }
pephubclient = { version = "==0.4.4", build = "pyhd8ed1ab_1" }
peppy = { version = "==0.40.8", build = "pyhd8ed1ab_0" }
pexpect = { version = "==4.9.0", build = "pyhd8ed1ab_1" }
pillow = { version = "==12.0.0", build = "py312h50c33e8_2" }
pip = { version = "==25.3", build = "pyh8b19718_0" }
pixman = { version = "==0.46.4", build = "h54a6638_1" }
platformdirs = { version = "==4.5.1", build = "pyhcf101f3_0" }
pluggy = { version = "==1.6.0", build = "pyhf9edf01_1" }
prompt-toolkit = { version = "==3.0.52", build = "pyha770c72_0" }
psutil = { version = "==7.1.3", build = "py312h5253ce2_0" }
pthread-stubs = { version = "==0.4", build = "hb9d3cd8_1002" }
ptyprocess = { version = "==0.7.0", build = "pyhd8ed1ab_1" }
pulp = { version = "==2.8.0", build = "py312hd0750ca_3" }
pure_eval = { version = "==0.2.3", build = "pyhd8ed1ab_1" }
pydantic = { version = "==2.12.5", build = "pyhcf101f3_1" }
pydantic-core = { version = "==2.41.5", build = "py312h868fb18_1" }
pygments = { version = "==2.19.2", build = "pyhd8ed1ab_0" }
pyparsing = { version = "==3.2.5", build = "pyhcf101f3_0" }
pyside6 = { version = "==6.10.1", build = "py312h9da60e5_0" }
pysocks = { version = "==1.7.1", build = "pyha55dd90_7" }
pytest = { version = "==9.0.2", build = "pyhcf101f3_0" }
python = { version = "==3.12.12", build = "hd63d673_1_cpython" }
python-dateutil = { version = "==2.9.0.post0", build = "pyhe01879c_2" }
python-fastjsonschema = { version = "==2.21.2", build = "pyhe01879c_0" }
python-tzdata = { version = "==2025.3", build = "pyhd8ed1ab_0" }
python_abi = { version = "==3.12", build = "8_cp312" }
pytz = { version = "==2025.2", build = "pyhd8ed1ab_0" }
pyyaml = { version = "==6.0.3", build = "py312h8a5da7c_0" }
qhull = { version = "==2020.2", build = "h434a139_5" }
qt6-main = { version = "==6.10.1", build = "h6f76662_2" }
readline = { version = "==8.3", build = "h853b02a_0" }
referencing = { version = "==0.37.0", build = "pyhcf101f3_0" }
requests = { version = "==2.32.5", build = "pyhd8ed1ab_0" }
reretry = { version = "==0.11.8", build = "pyhd8ed1ab_1" }
rich = { version = "==14.2.0", build = "pyhcf101f3_0" }
rpds-py = { version = "==0.30.0", build = "py312h868fb18_0" }
seqan-library = { version = "==2.4.0", build = "ha770c72_0" }
seqtk = { version = "==1.5", build = "h577a1d6_1" }
setuptools = { version = "==80.9.0", build = "pyhff2d567_0" }
shellingham = { version = "==1.5.4", build = "pyhd8ed1ab_2" }
six = { version = "==1.17.0", build = "pyhe01879c_1" }
slack-sdk = { version = "==3.39.0", build = "pyhd8ed1ab_0" }
slack_sdk = { version = "==3.39.0", build = "hd8ed1ab_0" }
smart_open = { version = "==7.5.0", build = "pyhcf101f3_0" }
smmap = { version = "==5.0.2", build = "pyhd8ed1ab_0" }
snakemake = { version = "==9.14.5", build = "hdfd78af_0" }
snakemake-interface-common = { version = "==1.22.0", build = "pyhd4c3c12_0" }
snakemake-interface-executor-plugins = { version = "==9.3.9", build = "pyhdfd78af_0" }
snakemake-interface-logger-plugins = { version = "==2.0.0", build = "pyhd4c3c12_0" }
snakemake-interface-report-plugins = { version = "==1.3.0", build = "pyhd4c3c12_0" }
snakemake-interface-scheduler-plugins = { version = "==2.0.2", build = "pyhd4c3c12_0" }
snakemake-interface-storage-plugins = { version = "==4.3.2", build = "pyhd4c3c12_0" }
snakemake-minimal = { version = "==9.14.5", build = "pyhdfd78af_0" }
stack_data = { version = "==0.6.3", build = "pyhd8ed1ab_1" }
tabulate = { version = "==0.9.0", build = "pyhcf101f3_3" }
tbb = { version = "==2022.3.0", build = "h8d10470_1" }
throttler = { version = "==1.2.2", build = "pyhd8ed1ab_0" }
tk = { version = "==8.6.13", build = "noxft_ha0e22de_103" }
tomli = { version = "==2.3.0", build = "pyhcf101f3_0" }
tornado = { version = "==6.5.3", build = "py312h4c3975b_0" }
traitlets = { version = "==5.14.3", build = "pyhd8ed1ab_1" }
typer = { version = "==0.20.0", build = "pyhefaf540_1" }
typer-slim = { version = "==0.20.0", build = "pyhcf101f3_1" }
typer-slim-standard = { version = "==0.20.0", build = "h4daf872_1" }
typing-extensions = { version = "==4.15.0", build = "h396c80c_0" }
typing-inspection = { version = "==0.4.2", build = "pyhd8ed1ab_1" }
typing_extensions = { version = "==4.15.0", build = "pyhcf101f3_0" }
tzdata = { version = "==2025c", build = "h8577fbf_0" }
ubiquerg = { version = "==0.8.0", build = "pyhd8ed1ab_0" }
unicodedata2 = { version = "==17.0.0", build = "py312h4c3975b_1" }
urllib3 = { version = "==2.6.2", build = "pyhd8ed1ab_0" }
veracitools = { version = "==0.1.3", build = "py_0" }
wayland = { version = "==1.24.0", build = "hd6090a7_1" }
wcwidth = { version = "==0.2.14", build = "pyhd8ed1ab_0" }
wheel = { version = "==0.45.1", build = "pyhd8ed1ab_1" }
wrapt = { version = "==1.17.3", build = "py312h4c3975b_1" }
xcb-util = { version = "==0.4.1", build = "h4f16b4b_2" }
xcb-util-cursor = { version = "==0.1.6", build = "hb03c661_0" }
xcb-util-image = { version = "==0.4.0", build = "hb711507_2" }
xcb-util-keysyms = { version = "==0.4.1", build = "hb711507_0" }
xcb-util-renderutil = { version = "==0.3.10", build = "hb711507_0" }
xcb-util-wm = { version = "==0.4.2", build = "hb711507_0" }
xkeyboard-config = { version = "==2.46", build = "hb03c661_0" }
xorg-libice = { version = "==1.1.2", build = "hb9d3cd8_0" }
xorg-libsm = { version = "==1.2.6", build = "he73a12e_0" }
xorg-libx11 = { version = "==1.8.12", build = "h4f16b4b_0" }
xorg-libxau = { version = "==1.0.12", build = "hb03c661_1" }
xorg-libxcomposite = { version = "==0.4.6", build = "hb9d3cd8_2" }
xorg-libxcursor = { version = "==1.2.3", build = "hb9d3cd8_0" }
xorg-libxdamage = { version = "==1.1.6", build = "hb9d3cd8_0" }
xorg-libxdmcp = { version = "==1.1.5", build = "hb03c661_1" }
xorg-libxext = { version = "==1.3.6", build = "hb9d3cd8_0" }
xorg-libxfixes = { version = "==6.0.2", build = "hb03c661_0" }
xorg-libxi = { version = "==1.8.2", build = "hb9d3cd8_0" }
xorg-libxrandr = { version = "==1.5.4", build = "hb9d3cd8_0" }
xorg-libxrender = { version = "==0.9.12", build = "hb9d3cd8_0" }
xorg-libxt = { version = "==1.3.1", build = "hb9d3cd8_0" }
xorg-libxtst = { version = "==1.2.5", build = "hb9d3cd8_3" }
xorg-libxxf86vm = { version = "==1.1.6", build = "hb9d3cd8_0" }
yaml = { version = "==0.2.5", build = "h280c20c_3" }
yte = { version = "==1.9.4", build = "pyhd8ed1ab_0" }
zlib-ng = { version = "==2.3.2", build = "h54a6638_0" }
zstd = { version = "==1.5.7", build = "hb78ec9c_6" }

[environments]
grthub-bclconvert = { features = ["grthub-bclconvert"], no-default-feature = true }
