#!/usr/bin/env bash
set -euo pipefail

# Run the whole workflow inside the container -- Snakemake driver included.
#
# The driver runs in the image and submits to SLURM through the host's sbatch,
# bind-mounted in (see scripts/container_binds.sh). Each job Snakemake spawns
# re-enters the same image via .container/bin/python, a shim this script
# generates. Two flags make that work, and neither is optional:
#
#   --shared-fs-usage without `software-deployment`
#       Snakemake otherwise puts its own sys.executable into the spawned
#       command, i.e. the in-container /app/.pixi/... path, which does not
#       exist on the compute node. Dropping software-deployment makes it emit a
#       bare `python`, which PATH can then resolve to the shim.
#   --precommand
#       Puts the shim directory first on the compute node's PATH.
#
# It contains no `$`: the slurm executor builds the sbatch call and runs it with
# shell=True *in the driver*, so anything unescaped would expand on the wrong
# side of the submission.
#
# For the host/pixi path (no container), use run_hpc3.sh instead.

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

# shellcheck source=scripts/find_singularity.sh
source "$here/scripts/find_singularity.sh"
# shellcheck source=scripts/container_binds.sh
source "$here/scripts/container_binds.sh"
# shellcheck source=scripts/read_config_key.sh
source "$here/scripts/read_config_key.sh"
# shellcheck source=scripts/require_slurm_account.sh
source "$here/scripts/require_slurm_account.sh"
# Secrets. Singularity passes the host environment through (no --cleanenv
# below), and SLURM's default --export=ALL carries it on to the compute nodes,
# so sourcing here is enough for every rule in the DAG.
# shellcheck source=scripts/load_dotenv.sh
source "$here/scripts/load_dotenv.sh"

SINGULARITY="$(find_singularity)"

# Image: $BCL_CONVERT_SIF wins, else the `container_sif` config key.
SIF="${BCL_CONVERT_SIF:-$(read_config_key container_sif || true)}"
if [[ -z "$SIF" ]]; then
    echo "Error: no container image. Set container_sif in snakemake_config.yaml" >&2
    echo "or export BCL_CONVERT_SIF=/path/to/bcl_convert.sif" >&2
    exit 1
fi
if [[ ! -r "$SIF" ]]; then
    echo "Error: cannot read container image $SIF" >&2
    echo "If this is the lab copy, check you are in group ucightf: id | grep ucightf" >&2
    exit 1
fi

# bcl-convert writes here; see the comment on CONTAINER_LOG_BIND.
mkdir -p "$CONTAINER_LOG_DIR"

BINDS="$(container_binds_flat "$SINGULARITY")"

# Generate the compute-node shim. Every path in it is absolute and resolved
# now, on the login node, because the compute node runs it from a bare `sh -c`
# with no module system, no pixi, and no repo-relative cwd guarantee.
SHIM_DIR="$here/.container/bin"
mkdir -p "$SHIM_DIR"
cat > "$SHIM_DIR/python" <<EOF
#!/bin/sh
# GENERATED by run_hpc3_container.sh -- edits are overwritten on the next run.
# Snakemake spawns compute-node jobs as \`python -m snakemake --mode remote\`.
# This is that python: it re-enters the container so the job runs in the same
# image as the driver that submitted it.

# /tmp is node-local. The launcher created this on the login node, which says
# nothing about the compute node, and singularity refuses to start when a bind
# source is missing:
#   FATAL: mount source $CONTAINER_LOG_DIR doesn't exist
mkdir -p $CONTAINER_LOG_DIR

# Singularity exports SINGULARITY_BIND into the container describing the binds
# it was started with. SLURM's default --export=ALL then carries that variable
# all the way to the compute node, where it would be merged with the explicit
# --bind flags below -- producing a duplicate of every mount ("destination is
# already in the mount point list") and dragging along login-node-only paths.
# The flags below are the single source of truth; drop the inherited copy.
unset SINGULARITY_BIND SINGULARITY_BINDPATH APPTAINER_BIND APPTAINER_BINDPATH

# The slurm executor hardcodes "--executor slurm-jobstep" into every spawned
# command. That executor then wraps the real work in \`srun\`, and srun launches
# its task on the HOST, outside this container -- while asking for the
# interpreter by the absolute in-container path, because
# snakemake_executor_plugin_slurm_jobstep.get_python_executable() returns
# sys.executable unconditionally (it extends RealExecutor, so it never gets the
# --shared-fs-usage conditional that RemoteExecutor has). The result is
#     error: execve(): /app/.pixi/envs/default/bin/python: No such file or directory
# No flag disables that srun, so override the executor instead: argparse takes
# the last occurrence, and appending wins over the hardcoded one. The job then
# runs directly in this container. It is still inside the allocation's cgroup,
# so SLURM's resource limits continue to apply; only srun's cpu-binding is lost.
case " \$* " in
    *" -m snakemake "*) exec $SINGULARITY exec --writable-tmpfs $BINDS \\
        "$SIF" /app/.pixi/envs/default/bin/python "\$@" --executor local ;;
esac

exec $SINGULARITY exec --writable-tmpfs $BINDS \\
    "$SIF" /app/.pixi/envs/default/bin/python "\$@"
EOF
chmod +x "$SHIM_DIR/python"

SNAKEMAKE_ARGS=(
    snakemake
    --profile profiles/hpc3
    # Without this, snakemake auto-merges profiles/default (the dragen-server
    # profile) and its settings win over --profile, silently reimposing
    # serial_operation=1 and blocking hpc3 job parallelism.
    --workflow-profile none
    # Everything except software-deployment. See the header.
    --shared-fs-usage persistence input-output sources source-cache
                      storage-local-copies software-deployment-cache
    --precommand "export PATH=$SHIM_DIR:/usr/local/bin:/usr/bin:/bin"
)

# Per-operator slurm account, from $SLURM_ACCOUNT (usually ~/.env, sourced by
# load_dotenv.sh above). Hard error when unset; see
# scripts/require_slurm_account.sh for why it is not a profile default and why
# unset cannot mean "let slurm decide".
require_slurm_account
SNAKEMAKE_ARGS+=("${SLURM_ACCOUNT_ARGS[@]}")

DRY_RUN=0
PASSTHROUGH_ARGS=()
for arg in "$@"; do
    case "$arg" in
        --dryrun|--dry-run) DRY_RUN=1 ;;
        *) PASSTHROUGH_ARGS+=("$arg") ;;
    esac
done
if [[ "$DRY_RUN" -eq 1 ]]; then
    SNAKEMAKE_ARGS+=(--dry-run)
fi
if [[ ${#PASSTHROUGH_ARGS[@]} -gt 0 ]]; then
    SNAKEMAKE_ARGS+=("${PASSTHROUGH_ARGS[@]}")
fi

# shellcheck disable=SC2086  # $BINDS is a deliberately word-split flag list
exec "$SINGULARITY" exec --writable-tmpfs $BINDS \
    --pwd "$here" "$SIF" "${SNAKEMAKE_ARGS[@]}"
